name = "All-Hands Template"
version = "0.1.0"
defaultTargets = ["UsingMathlib", "UsingCslib"]

[[require]]
name = "cslib"
git = "https://github.com/leanprover/cslib"
rev = "nightly-testing-2026-09-30"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "nightly-testing-2026-09-30"

[[lean_lib]]
name = "UsingMathlib"

[[lean_lib]]
name = "UsingCslib"
